$(INTDIR)\masm\idctmmx.obj: idctmmx.asm
$(INTDIR)\nasm\simple_idct_mmx.obj: simple_idct_mmx.asm
$(INTDIR)\nasm\skl_dct_sse.obj: skl_dct_sse.asm skl_nasm.h
$(INTDIR)\d2vparse.obj : d2vparse.cpp global.h misc.h resource.h pat.h
$(INTDIR)\getbit.obj : getbit.cpp global.h misc.h resource.h pat.h getbit.h AC3Dec\ac3.h
$(INTDIR)\gethdr.obj : gethdr.cpp global.h misc.h resource.h pat.h getbit.h
$(INTDIR)\getpic.obj : getpic.cpp global.h misc.h resource.h pat.h getbit.h
$(INTDIR)\gui.obj : gui.cpp resource.h global.h misc.h pat.h ..\config.h
$(INTDIR)\idctfpu.obj : idctfpu.cpp
$(INTDIR)\idctref.obj : idctref.cpp
$(INTDIR)\initial_parse.obj : initial_parse.cpp resource.h global.h misc.h pat.h
$(INTDIR)\misc.obj : misc.cpp global.h misc.h resource.h pat.h
$(INTDIR)\motion.obj : motion.cpp global.h misc.h resource.h pat.h getbit.h
$(INTDIR)\mpeg2dec.obj : mpeg2dec.cpp global.h misc.h resource.h pat.h getbit.h
$(INTDIR)\norm.obj : norm.cpp global.h misc.h resource.h pat.h
$(INTDIR)\parse_cli.obj : parse_cli.cpp resource.h global.h misc.h pat.h
$(INTDIR)\pat.obj : pat.cpp resource.h global.h misc.h pat.h
$(INTDIR)\store.obj : store.cpp global.h misc.h resource.h pat.h filter.h
$(INTDIR)\strverscmp.obj : strverscmp.cpp
$(INTDIR)\wavefs44.obj : wavefs44.cpp global.h misc.h resource.h pat.h
$(INTDIR)\AC3Dec\bit_allocate.obj : AC3Dec\bit_allocate.cpp AC3Dec\ac3.h
$(INTDIR)\AC3Dec\bitstream.obj : AC3Dec\bitstream.cpp AC3Dec\ac3.h AC3Dec\bitstream.h
$(INTDIR)\AC3Dec\coeff.obj : AC3Dec\coeff.cpp AC3Dec\ac3.h AC3Dec\bitstream.h
$(INTDIR)\AC3Dec\crc.obj : AC3Dec\crc.cpp AC3Dec\ac3.h
$(INTDIR)\AC3Dec\decode.obj : AC3Dec\decode.cpp global.h AC3Dec\ac3.h AC3Dec\bitstream.h
$(INTDIR)\AC3Dec\downmix.obj : AC3Dec\downmix.cpp global.h AC3Dec\ac3.h
$(INTDIR)\AC3Dec\exponent.obj : AC3Dec\exponent.cpp AC3Dec\ac3.h
$(INTDIR)\AC3Dec\imdct.obj : AC3Dec\imdct.cpp AC3Dec\ac3.h
$(INTDIR)\AC3Dec\parse.obj : AC3Dec\parse.cpp AC3Dec\ac3.h AC3Dec\bitstream.h
$(INTDIR)\AC3Dec\rematrix.obj : AC3Dec\rematrix.cpp AC3Dec\ac3.h
$(INTDIR)\AC3Dec\sanity_check.obj : AC3Dec\sanity_check.cpp AC3Dec\ac3.h
$(INTDIR)\gui.res : gui.rc resource.h ..\config.h
