//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gui.rc
//
#define ID_LEFT_BUTTON                  1
#define ID_LEFT_ARROW                   2
#define ID_RIGHT_BUTTON                 3
#define ID_RIGHT_ARROW                  4
#define ID_TRACKBAR                     5
#define ID_ADD                          6
#define ID_DEL                          7
#define ID_DELALL                       8
#define ID_UP                           9
#define ID_DOWN                         10
#define IDD_ABOUT                       11
#define IDC_GUI                         12
#define IDI_MOVIE                       13
#define IDI_SMALL                       14
#define IDR_ACCELERATOR                 15
#define IDD_INFO                        16
#define IDD_FILELIST                    17
#define IDD_LUMINANCE                   18
#define IDD_NORM                        19
#define IDD_CROPPING                    20
#define IDD_SET_PIDS                    21
#define IDD_DETECT_PIDS                 22
#define IDD_AVS_TEMPLATE                23
#define IDD_SELECT_TRACKS               24
#define IDD_BMP_PATH                    25
#define IDD_SELECT_DELAY_TRACK          26
#define IDD_SET_MARGIN                  27
#define IDC_CODED_NUMBER                1016
#define IDC_PLAYBACK_NUMBER             1017
#define IDC_FRAME_RATE                  1018
#define IDC_VOB_ID                      1019
#define IDC_CELL_ID                     1020
#define IDC_VIDEO_TYPE                  1021
#define IDC_FRAME_TYPE                  1022
#define IDC_ASPECT_RATIO                1023
#define IDC_REMAIN                      1024
#define IDC_ELAPSED                     1025
#define IDC_FRAME_SIZE                  1026
#define IDC_PROFILE                     1027
#define IDC_FPS                         1028
#define IDC_COLORIMETRY                 1029
#define IDC_TIMESTAMP                   1030
#define IDC_LIST                        1031
#define IDC_FRAME_REPEATS               1032
#define IDC_FIELD_REPEATS               1033
#define IDC_FRAME_STRUCTURE             1034
#define IDC_INFO                        1035
#define IDC_FIELD_ORDER                 1036
#define IDC_BITRATE                     1037
#define IDC_BITRATE_AVG                 1038
#define IDC_LUM_CHECK                   1039
#define IDC_NORM_SLIDER                 1040
#define IDC_NORM_CHECK                  1041
#define IDC_NORM                        1042
#define IDC_TOP_SLIDER                  1043
#define IDC_BOTTOM_SLIDER               1044
#define IDC_TOP                         1045
#define IDC_BOTTOM                      1046
#define IDC_RIGHT_SLIDER                1047
#define IDC_LEFT_SLIDER                 1048
#define IDC_RIGHT                       1049
#define IDC_LEFT                        1050
#define IDC_CROPPING_CHECK              1051
#define IDC_VERSION                     1052
#define IDC_HEIGHT                      1053
#define IDC_WIDTH                       1054
#define IDC_FWIDTH                      1055
#define IDC_FHEIGHT                     1056
#define IDC_VIDEO_PID                   1057
#define IDC_AUDIO_PID                   1058
#define IDC_PIDS_OK                     1059
#define IDC_PIDS_CANCEL                 1060
#define IDC_PID_LISTBOX                 1061
#define IDC_PCR_PID                     1062
#define IDC_SET_AUDIO                   1063
#define IDC_SET_VIDEO                   1064
#define IDC_SET_PCR                     1065
#define IDC_SET_DONE                    1066
#define IDC_AUDIO_TYPE                  1067
#define IDC_AUDIO_TYPE2                 1068
#define IDC_AUDIO_TYPE3                 1069
#define IDC_AUDIO_TYPE4                 1070
#define IDC_AUDIO_TYPE5                 1071
#define IDC_AUDIO_TYPE6                 1072
#define IDC_AUDIO_TYPE7                 1073
#define IDC_AUDIO_TYPE8                 1074
#define IDC_NO_TEMPLATE                 1075
#define IDC_CHANGE_TEMPLATE             1076
#define IDC_KEEP_TEMPLATE               1077
#define IDC_AVS_TEMPLATE                1078
#define IDC_GAMMA_SPIN                  1079
#define IDC_OFFSET_SPIN                 1080
#define IDC_GAMMA_BOX                   1081
#define IDC_OFFSET_BOX                  1082
#define IDC_STREAM_TYPE                 1083
#define IDC_TRACK_OK                    1084
#define IDC_TRACK_CANCEL                1085
#define IDC_AUDIO_LIST                  1086
#define IDC_TRACK_LIST                  1087
#define IDC_CODING_TYPE                 1088
#define IDC_BITRATE_MAX                 1089
#define IDC_CHANGE_BMP_PATH             1090
#define IDC_KEEP_BMP_PATH               1091
#define IDC_BMP_PATH                    1092
#define IDC_BMP_PATH_OK                 1093
#define IDC_BMP_PATH_CANCEL             1094
#define IDC_DISPLAY_SIZE                1095
#define IDC_DELAY_LIST                  1096
#define IDC_DELAY_OK                    1097
#define IDC_DELAY_CANCEL                1098
#define IDC_SEQUENCE                    1099
#define IDC_MARGIN                      1100
#define IDC_MARGIN_OK                   1101
#define IDC_MARGIN_CANCEL               1102
#define IDC_STATIC_ABOUT                1103
#define IDC_STATIC_THANK                1104
#define IDC_STATIC_OFFSET               1105
#define IDC_STATIC_GAMMA                1106
#define IDC_STATIC_VOLUME               1107
#define IDC_STATIC_VIDEO_PID            1108
#define IDC_STATIC_AUDIO_PID            1109
#define IDC_STATIC_PCR_PID              1110
#define IDC_STATIC_SET_PIDS             1111
#define IDC_STATIC_AVS_TEMPLATE         1112
#define IDC_STATIC_BMP_PATH             1113
#define IDC_STATIC_FLEFT                1114
#define IDC_STATIC_FRIGHT               1115
#define IDC_STATIC_FTOP                 1116
#define IDC_STATIC_FBOTTOM              1117
#define IDC_STATIC_DETECT_PIDS          1118
#define IDC_STATIC_SELECT_TRACKS        1119
#define IDC_STATIC_SELECT_DELAY_TRACK   1120
#define IDC_STATIC_SET_MARGIN           1121
#define IDC_STATIC_MSEC                 1122
#define IDC_SELECT_VIDEO_PID            1123
#define IDC_SELECT_AUDIO_PID            1124
#define IDC_SELECT_PCR_PID              1125
#define IDM_ABOUT                       32769
#define IDM_EXIT                        32770
#define IDM_OPEN                        32771
#define IDM_SAVE_D2V                    32772
#define IDM_LOAD_D2V                    32774
#define IDM_PREVIEW                     32775
#define IDM_PREVIEW_NO_INFO             32776
#define IDM_PAUSE                       32777
#define IDM_STOP                        32778
#define IDM_DISPLAY                     32779
#define IDM_PP_HIGH                     32780
#define IDM_PP_NORMAL                   32781
#define IDM_PP_LOW                      32782
#define IDM_FO_FILM                     32784
#define IDM_INFO                        32785
#define IDM_DIRECTDRAW                  32786
#define IDM_VFAPI                       32787
#define IDM_IDCT_MMX                    32788
#define IDM_IDCT_FPU                    32789
#define IDM_IDCT_REF                    32790
#define IDM_MMX                         32791
#define IDM_SSEMMX                      32792
#define IDM_SRC_NONE                    32795
#define IDM_SRC_LOW                     32796
#define IDM_SRC_MID                     32797
#define IDM_SRC_HIGH                    32798
#define IDM_SRC_UHIGH                   32799
#define IDM_NORM                        32800
#define IDM_TRACK_1                     32801
#define IDM_TRACK_2                     32802
#define IDM_TRACK_3                     32803
#define IDM_TRACK_4                     32804
#define IDM_TRACK_5                     32805
#define IDM_TRACK_6                     32806
#define IDM_TRACK_7                     32807
#define IDM_TRACK_8                     32808
#define IDM_TVSCALE                     32809
#define IDM_PCSCALE                     32810
#define IDM_BMP                         32811
#define IDM_LUMINANCE                   32812
#define IDM_DSDOWN                      32813
#define IDM_FO_NONE                     32814
#define IDM_DRC_NONE                    32815
#define IDM_DRC_LIGHT                   32816
#define IDM_DRC_NORMAL                  32817
#define IDM_DRC_HEAVY                   32818
#define IDM_CROPPING                    32819
#define IDM_PRESCALE                    32820
#define IDM_IDCT_SSEMMX                 32821
#define IDM_3DNOW                       32822
#define IDM_SSEFPU                      32823
#define IDM_SSE2                        32827
#define IDM_IDCT_SSE2MMX                32828
#define IDM_DEMUX                       32829
#define IDM_DEMUXALL                    32830
#define IDM_DECODE                      32831
#define IDM_AUDIO_NONE                  32832
#define IDM_PLAY                        32834
#define IDM_JACKEI                      32835
#define IDM_NEURON2                     32836
#define IDM_FO_RAW                      32837
#define IDM_SET_PIDS                    32838
#define IDM_DETECT_PIDS                 32839
#define IDM_DETECT_PIDS_PSIP            32840
#define IDM_DETECT_PIDS_RAW             32841
#define IDM_SAVE_D2V_AND_DEMUX          32842
#define IDM_PARSE_D2V                   32843
#define IDM_FIX_D2V                     32844
#define IDM_IDCT_SKAL                   32845
#define IDM_IDCT_SIMPLE                 32846
#define IDM_LOG_QUANTS                  32847
#define IDM_SPEED_SUPER_SLOW            32848
#define IDM_SPEED_SLOW                  32849
#define IDM_SPEED_NORMAL                32850
#define IDM_SPEED_FAST                  32851
#define IDM_SPEED_MAXIMUM               32852
#define IDM_FORCE_OPEN                  32853
#define IDM_SPEED_SINGLE_STEP           32854
#define IDM_DGINDEX_MANUAL              32855
#define IDM_DGDECODE_MANUAL             32856
#define IDM_QUICK_START                 32857
#define IDM_AVS_TEMPLATE                32859
#define IDM_FULL_PATH                   32860
#define IDM_LOG_TIMESTAMPS              32862
#define IDM_FUSION_AUDIO                32863
#define IDM_DEMUX_AUDIO                 32864
#define IDM_TRACK_NUMBER                32865
#define IDM_SYNC1                       32866
#define IDM_SYNC2                       32867
#define IDM_SYNC3                       32868
#define IDM_SYNC4                       32869
#define IDM_SYNC5                       32870
#define IDM_SYNC6                       32871
#define IDM_SYNC7                       32872
#define IDM_SYNC8                       32873
#define IDM_LOOP_PLAYBACK               32874
#define IDM_SHRINK_BY_HALF              32875
#define IDM_TOP_LEFT                    32876
#define IDM_TOP_RIGHT                   32877
#define IDM_BOTTOM_LEFT                 32878
#define IDM_BOTTOM_RIGHT                32879
#define IDM_BMP_PATH                    32880
#define IDM_INFO_LOG                    32881
#define IDM_ANALYZESYNC                 32882
#define ID_FILE_CLOSE                   32883
#define IDM_CLOSE                       32883
#define IDM_COPYFRAMETOCLIPBOARD        32884
#define IDM_FULL_SIZED                  32885
#define IDM_SET_MARGIN                  32886
#define IDM_CFOT_DISABLE                32887
#define IDM_CFOT_ENABLE                 32888
#define ID_MRU_FILE0                    50000
#define ID_MRU_FILE1                    50001
#define ID_MRU_FILE2                    50002
#define ID_MRU_FILE3                    50003
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        28
#define _APS_NEXT_COMMAND_VALUE         32889
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
